//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dim.AirConditioner.Control.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AirConditionerControlVoiceCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AirConditionerControlVoiceCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dim.AirConditioner.Control.Cli.AirConditionerControlVoiceCommands", typeof(AirConditionerControlVoiceCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar temperatura a.
        /// </summary>
        internal static string ChangeTemperatureCommand {
            get {
                return ResourceManager.GetString("ChangeTemperatureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfríar la habitación a.
        /// </summary>
        internal static string CoolRoom {
            get {
                return ResourceManager.GetString("CoolRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajar temperatura a.
        /// </summary>
        internal static string CoolRoom2 {
            get {
                return ResourceManager.GetString("CoolRoom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducir temperatura a.
        /// </summary>
        internal static string CoolRoom3 {
            get {
                return ResourceManager.GetString("CoolRoom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura actual.
        /// </summary>
        internal static string CurrentTemperatureCommand {
            get {
                return ResourceManager.GetString("CurrentTemperatureCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados.
        /// </summary>
        internal static string DegreesKeyWord {
            get {
                return ResourceManager.GetString("DegreesKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calentar la habitación a.
        /// </summary>
        internal static string HeatRoom {
            get {
                return ResourceManager.GetString("HeatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumentar temperatura a.
        /// </summary>
        internal static string HeatRoom2 {
            get {
                return ResourceManager.GetString("HeatRoom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir temperatura a.
        /// </summary>
        internal static string HeatRoom3 {
            get {
                return ResourceManager.GetString("HeatRoom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar aire acondicionado.
        /// </summary>
        internal static string PowerOffCommand {
            get {
                return ResourceManager.GetString("PowerOffCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encender aire acondicionado.
        /// </summary>
        internal static string PowerOnCommand {
            get {
                return ResourceManager.GetString("PowerOnCommand", resourceCulture);
            }
        }
    }
}
