//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dim.AirConditioner.Control.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AirConditionerSpeechResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AirConditionerSpeechResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dim.AirConditioner.Control.Cli.AirConditionerSpeechResponses", typeof(AirConditionerSpeechResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El aire acondicionado ya estaba apagado..
        /// </summary>
        internal static string AlreadyOff {
            get {
                return ResourceManager.GetString("AlreadyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El aire acondicionado ya estaba encendido..
        /// </summary>
        internal static string AlreadyOn {
            get {
                return ResourceManager.GetString("AlreadyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfriando la habitación a {0} grados centígrados..
        /// </summary>
        internal static string CoolingRoomToTemperature {
            get {
                return ResourceManager.GetString("CoolingRoomToTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La temperatura actual en la habitación es de {0} grados centígrados..
        /// </summary>
        internal static string CurrentTemperatureResponse {
            get {
                return ResourceManager.GetString("CurrentTemperatureResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha activado el aire acondicionado..
        /// </summary>
        internal static string FailStartingUp {
            get {
                return ResourceManager.GetString("FailStartingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calentando la habitación a {0} grados centígrados..
        /// </summary>
        internal static string HeatingRoomToTemperature {
            get {
                return ResourceManager.GetString("HeatingRoomToTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aire acondicionado encendido..
        /// </summary>
        internal static string PoweredOn {
            get {
                return ResourceManager.GetString("PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aire acondicionado apagado..
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Apagando aire acondicionado.&quot;).
        /// </summary>
        internal static string TurningOff {
            get {
                return ResourceManager.GetString("TurningOff", resourceCulture);
            }
        }
    }
}
